### PR TITLE
Update my previous entry

### PR DESCRIPTION
**Pull request by ryanoconnor7**
Added description on custom playground book tool.

### CODE REVIEW

**Comment by kylespadaro-zz** [comment]
That technologies addition is a bit long, could you try to shorten it?

**Comment by ryanoconnor7** [comment]
How does it look now?

**Comment by ryanoconnor7** [comment]
trimmed a bit more

**Comment by kylespadaro-zz** [comment]
I'll merge it, then see how it looks. It should be good. Good luck!

**Pull request merged**
