### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wow-such-amazing**
Added my project :)

### CODE REVIEW

**Comment by kylespadaro-zz** [comment]
Just put your entry in alphabetical order by first name before I can merge. Thanks!

**Comment by wow-such-amazing** [comment]
Replaced :)

**Comment by kylespadaro-zz** [comment]
I'm unable to merge this because there are conflicts preventing me from doing so. Try to fix if you can!

**Comment by wow-such-amazing** [comment]
i'll just create new PR

**Comment by kylespadaro-zz** [comment]
I merged your new PR so you're good. Good luck!

**Pull request closed without merging**
