### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ryanoconnor7**

### CODE REVIEW

**Comment by AndrewKe** [comment]
Good luck!

**Comment by ryanoconnor7** [comment]
@AndrewKe thanks, you too!

**Comment by ryanoconnor7** [comment]
Hey, would it be worth it to add a hyperlink on the technology `PlaygroundBook` that I used? It was a custom tool by Ash Furrow, and I think it'd be helpful for other people.

**Comment by kylespadaro-zz** [comment]
Sure, if you'd like.

**Pull request merged**
